In [28]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
%matplotlib inline

df_train = pd.read_csv("/home/priyansh/Desktop/shell/big_mart/train.csv")
df_test = pd.read_csv("/home/priyansh/Desktop/shell/big_mart/test.csv")

df_train['source']='train'
df_test['source']='test'

df = pd.concat([df_train,df_test],ignore_index=True)

In [2]:
df.head()

,Item_Fat_Content,Item_Identifier,Item_MRP,Item_Outlet_Sales,Item_Type,Item_Visibility,Item_Weight,Outlet_Establishment_Year,Outlet_Identifier,Outlet_Location_Type,Outlet_Size,Outlet_Type
0,Low Fat,FDA15,249.8092,3735.1380,Dairy,0.016047,9.30,1999,OUT049,Tier 1,Medium,Supermarket Type1
1,Regular,DRC01,48.2692,443.4228,Soft Drinks,0.019278,5.92,2009,OUT018,Tier 3,Medium,Supermarket Type2
2,Low Fat,FDN15,141.6180,2097.2700,Meat,0.016760,17.50,1999,OUT049,Tier 1,Medium,Supermarket Type1
3,Regular,FDX07,182.0950,732.3800,Fruits and Vegetables,0.000000,19.20,1998,OUT010,Tier 3,NaN,Grocery Store
4,Low Fat,NCD19,53.8614,994.7052,Household,0.000000,8.93,1987,OUT013,Tier 3,High,Supermarket Type1

In [3]:
df.Item_Type.unique()

array(['Dairy', 'Soft Drinks', 'Meat', 'Fruits and Vegetables',
       'Household', 'Baking Goods', 'Snack Foods', 'Frozen Foods',
       'Breakfast', 'Health and Hygiene', 'Hard Drinks', 'Canned',
       'Breads', 'Starchy Foods', 'Others', 'Seafood'], dtype=object)

In [4]:
df.describe()

/home/priyansh/anaconda3/lib/python3.5/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,Item_MRP,Item_Outlet_Sales,Item_Visibility,Item_Weight,Outlet_Establishment_Year
count,14204.000000,8523.000000,14204.000000,11765.000000,14204.000000
mean,141.004977,2181.288914,0.065953,12.792854,1997.830681
std,62.086938,1706.499616,0.051459,4.652502,8.371664
min,31.290000,33.290000,0.000000,4.555000,1985.000000
25%,94.012000,NaN,0.027036,NaN,1987.000000
50%,142.247000,NaN,0.054021,NaN,1999.000000
75%,185.855600,NaN,0.094037,NaN,2004.000000
max,266.888400,13086.964800,0.328391,21.350000,2009.000000

In [5]:
print(df["Item_Type"].value_counts())

Fruits and Vegetables    2013
Snack Foods              1989
Household                1548
Frozen Foods             1426
Dairy                    1136
Baking Goods             1086
Canned                   1084
Health and Hygiene        858
Meat                      736
Soft Drinks               726
Breads                    416
Hard Drinks               362
Others                    280
Starchy Foods             269
Breakfast                 186
Seafood                    89
Name: Item_Type, dtype: int64

In [6]:
print(df["Outlet_Type"].value_counts())

Supermarket Type1    9294
Grocery Store        1805
Supermarket Type3    1559
Supermarket Type2    1546
Name: Outlet_Type, dtype: int64

In [7]:
sale = df["Item_Fat_Content"].value_counts()
df["Item_Fat_Content"]=df["Item_Fat_Content"].replace({'LF':'Low Fat','reg':'Regular','low fat':'Low Fat'})
print(df["Item_Fat_Content"].value_counts())

Low Fat    9185
Regular    5019
Name: Item_Fat_Content, dtype: int64

In [8]:
df.apply(lambda x: len(x.unique()))

Item_Fat_Content                 2
Item_Identifier               1559
Item_MRP                      8052
Item_Outlet_Sales             3494
Item_Type                       16
Item_Visibility              13006
Item_Weight                    416
Outlet_Establishment_Year        9
Outlet_Identifier               10
Outlet_Location_Type             3
Outlet_Size                      4
Outlet_Type                      4
dtype: int64

In [9]:
weight_table = df.pivot_table(values="Item_Weight",index="Item_Identifier")
miss_val = df["Item_Weight"].isnull()
df.loc[miss_val,'Item_Weight'] = df.loc[miss_val,'Item_Identifier'].apply(lambda x: weight_table[x])

In [10]:
df.describe()

/home/priyansh/anaconda3/lib/python3.5/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,Item_MRP,Item_Outlet_Sales,Item_Visibility,Item_Weight,Outlet_Establishment_Year
count,14204.000000,8523.000000,14204.000000,14204.000000,14204.000000
mean,141.004977,2181.288914,0.065953,12.793380,1997.830681
std,62.086938,1706.499616,0.051459,4.651716,8.371664
min,31.290000,33.290000,0.000000,4.555000,1985.000000
25%,94.012000,NaN,0.027036,8.710000,1987.000000
50%,142.247000,NaN,0.054021,12.600000,1999.000000
75%,185.855600,NaN,0.094037,16.750000,2004.000000
max,266.888400,13086.964800,0.328391,21.350000,2009.000000

In [11]:
df.Outlet_Type.unique()

array(['Supermarket Type1', 'Supermarket Type2', 'Grocery Store',
       'Supermarket Type3'], dtype=object)

In [12]:
df["Outlet_Size"].value_counts()
missing_values = df['Outlet_Size'].isnull() 
df.loc[missing_values,"Outlet_Size"] = df.loc[missing_values,"Outlet_Type"].apply(lambda x: "Medium")
missing_values2 = df['Outlet_Size'].isnull()
df.describe()

/home/priyansh/anaconda3/lib/python3.5/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,Item_MRP,Item_Outlet_Sales,Item_Visibility,Item_Weight,Outlet_Establishment_Year
count,14204.000000,8523.000000,14204.000000,14204.000000,14204.000000
mean,141.004977,2181.288914,0.065953,12.793380,1997.830681
std,62.086938,1706.499616,0.051459,4.651716,8.371664
min,31.290000,33.290000,0.000000,4.555000,1985.000000
25%,94.012000,NaN,0.027036,8.710000,1987.000000
50%,142.247000,NaN,0.054021,12.600000,1999.000000
75%,185.855600,NaN,0.094037,16.750000,2004.000000
max,266.888400,13086.964800,0.328391,21.350000,2009.000000

In [13]:
df.head()

,Item_Fat_Content,Item_Identifier,Item_MRP,Item_Outlet_Sales,Item_Type,Item_Visibility,Item_Weight,Outlet_Establishment_Year,Outlet_Identifier,Outlet_Location_Type,Outlet_Size,Outlet_Type
0,Low Fat,FDA15,249.8092,3735.1380,Dairy,0.016047,9.30,1999,OUT049,Tier 1,Medium,Supermarket Type1
1,Regular,DRC01,48.2692,443.4228,Soft Drinks,0.019278,5.92,2009,OUT018,Tier 3,Medium,Supermarket Type2
2,Low Fat,FDN15,141.6180,2097.2700,Meat,0.016760,17.50,1999,OUT049,Tier 1,Medium,Supermarket Type1
3,Regular,FDX07,182.0950,732.3800,Fruits and Vegetables,0.000000,19.20,1998,OUT010,Tier 3,Medium,Grocery Store
4,Low Fat,NCD19,53.8614,994.7052,Household,0.000000,8.93,1987,OUT013,Tier 3,High,Supermarket Type1

In [14]:
visibility = df.pivot_table(values="Item_Visibility",index="Item_Identifier")
missing_val = (df["Item_Visibility"] == 0)
df.loc[missing_val,"Item_Visibility"] = df.loc[missing_val,"Item_Identifier"].apply(lambda x: visibility[x])

In [15]:
df.describe()

/home/priyansh/anaconda3/lib/python3.5/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,Item_MRP,Item_Outlet_Sales,Item_Visibility,Item_Weight,Outlet_Establishment_Year
count,14204.000000,8523.000000,14204.000000,14204.000000,14204.000000
mean,141.004977,2181.288914,0.069710,12.793380,1997.830681
std,62.086938,1706.499616,0.049728,4.651716,8.371664
min,31.290000,33.290000,0.003575,4.555000,1985.000000
25%,94.012000,NaN,0.031145,8.710000,1987.000000
50%,142.247000,NaN,0.057194,12.600000,1999.000000
75%,185.855600,NaN,0.096930,16.750000,2004.000000
max,266.888400,13086.964800,0.328391,21.350000,2009.000000

In [16]:
df["Outlet_Years"] = 2013 - df["Outlet_Establishment_Year"]
df["Outlet_Years"].describe()

count    14204.000000
mean        15.169319
std          8.371664
min          4.000000
25%          9.000000
50%         14.000000
75%         26.000000
max         28.000000
Name: Outlet_Years, dtype: float64

In [17]:
#Get the first two characters of ID:
df['Item_Broad_Category'] = df['Item_Identifier'].apply(lambda x: x[0:2])
df['Item_Broad_Category'] = df['Item_Broad_Category'].map({'FD':'Food','NC':'Non-Consumable','DR':'Drinks'})
df['Item_Broad_Category'].value_counts()

Food              10201
Non-Consumable     2686
Drinks             1317
Name: Item_Broad_Category, dtype: int64

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df["Outlet"]=le.fit_transform(df["Outlet_Identifier"])
var_mod = ["Item_Fat_Content","Outlet_Location_Type","Outlet_Size","Item_Broad_Category","Outlet_Type","Outlet"]

for i in var_mod:
    df[i]=le.fit_transform(df[i])

In [24]:
pd.get_dummies(df,columns=["Item_Fat_Content","Outlet_Location_Type","Outlet_Size","Item_Broad_Category","Outlet_Type","Outlet"])

,Item_Identifier,Item_MRP,Item_Outlet_Sales,Item_Type,Item_Visibility,Item_Weight,Outlet_Establishment_Year,Outlet_Identifier,Outlet_Years,Item_Fat_Content_0,...,Outlet_0,Outlet_1,Outlet_2,Outlet_3,Outlet_4,Outlet_5,Outlet_6,Outlet_7,Outlet_8,Outlet_9
0,FDA15,249.8092,3735.1380,Dairy,0.016047,9.300,1999,OUT049,14,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,DRC01,48.2692,443.4228,Soft Drinks,0.019278,5.920,2009,OUT018,4,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,FDN15,141.6180,2097.2700,Meat,0.016760,17.500,1999,OUT049,14,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,FDX07,182.0950,732.3800,Fruits and Vegetables,0.017834,19.200,1998,OUT010,15,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,NCD19,53.8614,994.7052,Household,0.009780,8.930,1987,OUT013,26,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,FDP36,51.4008,556.6088,Baking Goods,0.057059,10.395,2009,OUT018,4,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6,FDO10,57.6588,343.5528,Snack Foods,0.012741,13.650,1987,OUT013,26,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,FDP10,107.7622,4022.7636,Snack Foods,0.127470,19.000,1985,OUT027,28,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
8,FDH17,96.9726,1076.5986,Frozen Foods,0.016687,16.200,2002,OUT045,11,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9,FDU28,187.8214,4710.5350,Frozen Foods,0.094450,19.200,2007,OUT017,6,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,FDY07,45.5402,1516.0266,Fruits and Vegetables,0.040627,11.800,1999,OUT049,14,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11,FDA03,144.1102,2187.1530,Dairy,0.045464,18.500,1997,OUT046,16,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
12,FDX32,145.4786,1589.2646,Fruits and Vegetables,0.100014,15.100,1999,OUT049,14,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
13,FDS46,119.6782,2145.2076,Snack Foods,0.047257,17.600,1997,OUT046,16,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
14,FDF32,196.4426,1977.4260,Fruits and Vegetables,0.068024,16.350,1987,OUT013,26,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,FDP49,56.3614,1547.3192,Breakfast,0.069089,9.000,1997,OUT046,16,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
16,NCB42,115.3492,1621.8888,Health and Hygiene,0.008596,11.800,2009,OUT018,4,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
17,FDP49,54.3614,718.3982,Breakfast,0.069196,9.000,1999,OUT049,14,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
18,DRI11,113.2834,2303.6680,Hard Drinks,0.034238,8.260,1985,OUT027,28,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
19,FDU02,230.5352,2748.4224,Dairy,0.102492,13.350,2004,OUT035,9,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
20,FDN22,250.8724,3775.0860,Snack Foods,0.138190,18.850,1987,OUT013,26,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,FDW12,144.5444,4064.0432,Baking Goods,0.035400,8.315,1985,OUT027,28,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
22,NCB30,196.5084,1587.2672,Household,0.025698,14.600,2004,OUT035,9,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
23,FDC37,107.6938,214.3876,Baking Goods,0.057557,15.500,1985,OUT019,28,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
24,FDR28,165.0210,4078.0250,Frozen Foods,0.025896,13.850,1997,OUT046,16,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
25,NCD06,45.9060,838.9080,Household,0.099887,13.000,2007,OUT017,6,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,FDV10,42.3112,1065.2800,Snack Foods,0.066693,7.645,2004,OUT035,9,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
27,DRJ59,39.1164,308.9312,Hard Drinks,0.019356,11.650,1987,OUT013,26,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,FDE51,45.5086,178.4344,Dairy,0.161467,5.925,1998,OUT010,15,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,FDC14,43.6454,125.8362,Canned,0.072222,14.500,1985,OUT019,28,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14174,FDD23,186.1898,NaN,Starchy Foods,0.048645,9.500,1987,OUT013,26,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14175,FDP32,126.7678,NaN,Fruits and Vegetables,0.087847,6.650,2002,OUT045,11,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
14176,FDO31,80.2960,NaN,Fruits and Vegetables,0.028977,6.760,2004,OUT035,9,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
14177,FDQ57,144.5760,NaN,Snack Foods,0.024077,7.275,1987,OUT013,26,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14178,FDX32,143.6786,NaN,Fruits and Vegetables,0.099375,15.100,1985,OUT027,28,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
14179,FDC39,207.8296,NaN,Dairy,0.158425,7.405,1985,OUT027,28,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
14180,FDU55,261.3278,NaN,Fruits and Vegetables,0.035911,16.200,1997,OUT046,16,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
14181,FDL45,123.4704,NaN,Snack Foods,0.037656,15.600,1987,OUT013,26,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14182,DRK37,188.8530,NaN,Soft Drinks,0.044073,5.000,1999,OUT049,14,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14183,FDK22,215.3850,NaN,Snack Foods,0.026065,9.800,1987,OUT013,26,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14184,DRG37,155.7972,NaN,Soft Drinks,0.020225,16.200,1985,OUT027,28,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
14185,FDK22,214.3850,NaN,Snack Foods,0.026234,9.800,2007,OUT017,6,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14186,DRH36,72.8696,NaN,Soft Drinks,0.033516,16.200,2009,OUT018,4,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
14187,DRC36,173.4054,NaN,Soft Drinks,0.045168,13.000,2009,OUT018,4,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
14188,DRE03,46.0718,NaN,Dairy,0.024110,19.600,1985,OUT027,28,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
14189,FDF34,196.9084,NaN,Snack Foods,0.014019,9.300,1997,OUT046,16,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
14190,FDZ22,82.1250,NaN,Snack Foods,0.045270,9.395,1997,OUT046,16,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
14191,FDC44,115.1518,NaN,Fruits and Vegetables,0.288892,15.600,1998,OUT010,15,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14192,FDN31,188.0530,NaN,Fruits and Vegetables,0.072529,11.500,1985,OUT027,28,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
14193,FDO03,229.4352,NaN,Meat,0.037092,10.395,2007,OUT017,6,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14194,FDA01,59.5904,NaN,Canned,0.054463,15.000,1999,OUT049,14,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14195,NCH42,231.1010,NaN,Household,0.036594,6.860,1999,OUT049,14,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14196,FDF46,116.0834,NaN,Snack Foods,0.094053,7.070,2009,OUT018,4,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
14197,DRL35,43.2770,NaN,Hard Drinks,0.030704,15.700,1997,OUT046,16,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
14198,FDW46,63.4484,NaN,Snack Foods,0.070411,13.000,1999,OUT049,14,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14199,FDB58,141.3154,NaN,Snack Foods,0.013496,10.500,1997,OUT046,16,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
14200,FDD47,169.1448,NaN,Starchy Foods,0.142991,7.600,2009,OUT018,4,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
14201,NCO17,118.7440,NaN,Health and Hygiene,0.073529,10.000,2002,OUT045,11,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
14202,FDJ26,214.6218,NaN,Canned,0.088380,15.300,2007,OUT017,6,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14203,FDU37,79.7960,NaN,Canned,0.104720,9.500,2002,OUT045,11,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [26]:
df.dtypes

Item_Fat_Content               int64
Item_Identifier               object
Item_MRP                     float64
Item_Outlet_Sales            float64
Item_Type                     object
Item_Visibility              float64
Item_Weight                  float64
Outlet_Establishment_Year      int64
Outlet_Identifier             object
Outlet_Location_Type           int64
Outlet_Size                    int64
Outlet_Type                    int64
Outlet_Years                   int64
Item_Broad_Category            int64
Outlet                         int64
dtype: object

In [29]:
df.drop(["Outlet_Establishment_Year","Item_Type"],axis=1,inplace=True)

train_data = df.loc[df['source']=="train"]
test_data = df.loc[df['source']=="test"]

#Drop unnecessary columns:
test_data.drop(['Item_Outlet_Sales','source'],axis=1,inplace=True)
train_data.drop(['source'],axis=1,inplace=True)

#Export files as modified versions:
train_data.to_csv("train_modified.csv",index=False)
test_data.to_csv("test_modified.csv",index=False)

/home/priyansh/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/priyansh/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [31]:
#baseline solution
mean = train_data['Item_Outlet_Sales'].mean()

sol_1 = test_data[['Item_Identifier','Outlet_Identifier']]
sol_1['Item_Outlet_Sales'] = mean

sol_1.to_csv("solution_base.csv",index=False)

/home/priyansh/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy